import os
import json
from google_auth_oauthlib.flow import InstalledAppFlow

# Define the permissions we need
SCOPES = [
    'https://www.googleapis.com/auth/gmail.send',
    'https://www.googleapis.com/auth/gmail.readonly',
    'https://www.googleapis.com/auth/drive.readonly'
]

def main():
    # 1. Load the client config from credentials_py.py
    try:
        import credentials_py
        client_config = credentials_py.CREDENTIALS
    except ImportError:
        print("ERROR: 'credentials_py.py' not found.")
        return

    # 2. Run the OAuth Flow
    try:
        flow = InstalledAppFlow.from_client_config(client_config, SCOPES)
        creds = flow.run_local_server(port=0)
    except Exception as e:
        print(f"Authentication failed: {e}")
        return

    # 3. Save the token as a Python file (token_py.py)
    token_data = json.loads(creds.to_json())
    
    with open('token_py.py', 'w') as f:
        f.write("# This file is auto-generated by oauth_setup.py\n")
        f.write("TOKEN = ")
        json.dump(token_data, f, indent=4)
        f.write("\n")
    
    print("SUCCESS! 'token_py.py' has been created.")

if __name__ == '__main__':
    main()